version: "3.0"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "9001:9000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_DATABASE=app
      - DB_CONNECTION=mysql
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
  db:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_HOST=%
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3307:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge